name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    #secrets: inherit
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for pre-commit to detect changed files

      - name: Setup token for Python installation
        run: git config --global url."https://${{ secrets.MY_USERNAME }}:${{ secrets.MY_TOKEN }}@github.com".insteadOf ssh://git@github.com # replace with whatever authentication method you're currently using

      - name: Set up the environment
        uses: ./.github/actions/setup-venv

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Run uv lock check
        run: uv lock --locked

      - name: Run pre-commit
        run: uv run --no-project pre-commit run --show-diff-on-failure --color=always --all-files

      # - name: Run test
      #   run: uv run inv tests.run

  # check-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v4

  #     - name: Set up the environment
  #       uses: ./.github/actions/setup-venv

  #     - name: Check if documentation can be built
  #       run: uv run mkdocs build -s
